(cl:defpackage assignment_1-srv
  (:use )
  (:export
   "GET_POS"
   "<GET_POS-REQUEST>"
   "GET_POS-REQUEST"
   "<GET_POS-RESPONSE>"
   "GET_POS-RESPONSE"
   "REACH_NEXT_POS"
   "<REACH_NEXT_POS-REQUEST>"
   "REACH_NEXT_POS-REQUEST"
   "<REACH_NEXT_POS-RESPONSE>"
   "REACH_NEXT_POS-RESPONSE"
  ))

