// Generated by gencpp from file assignment_1/get_posRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_1_MESSAGE_GET_POSREQUEST_H
#define ASSIGNMENT_1_MESSAGE_GET_POSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_1
{
template <class ContainerAllocator>
struct get_posRequest_
{
  typedef get_posRequest_<ContainerAllocator> Type;

  get_posRequest_()
    : minx(0)
    , maxx(0)
    , miny(0)
    , maxy(0)  {
    }
  get_posRequest_(const ContainerAllocator& _alloc)
    : minx(0)
    , maxx(0)
    , miny(0)
    , maxy(0)  {
  (void)_alloc;
    }



   typedef int64_t _minx_type;
  _minx_type minx;

   typedef int64_t _maxx_type;
  _maxx_type maxx;

   typedef int64_t _miny_type;
  _miny_type miny;

   typedef int64_t _maxy_type;
  _maxy_type maxy;





  typedef boost::shared_ptr< ::assignment_1::get_posRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_1::get_posRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_posRequest_

typedef ::assignment_1::get_posRequest_<std::allocator<void> > get_posRequest;

typedef boost::shared_ptr< ::assignment_1::get_posRequest > get_posRequestPtr;
typedef boost::shared_ptr< ::assignment_1::get_posRequest const> get_posRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_1::get_posRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_1::get_posRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::get_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::get_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::get_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::get_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::get_posRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::get_posRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_1::get_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "997f9bce9b979590fcbd1f50d2d0fe9c";
  }

  static const char* value(const ::assignment_1::get_posRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x997f9bce9b979590ULL;
  static const uint64_t static_value2 = 0xfcbd1f50d2d0fe9cULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_1::get_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_1/get_posRequest";
  }

  static const char* value(const ::assignment_1::get_posRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_1::get_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 minx\n\
int64 maxx\n\
int64 miny\n\
int64 maxy\n\
";
  }

  static const char* value(const ::assignment_1::get_posRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_1::get_posRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.minx);
      stream.next(m.maxx);
      stream.next(m.miny);
      stream.next(m.maxy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_posRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_1::get_posRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_1::get_posRequest_<ContainerAllocator>& v)
  {
    s << indent << "minx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.minx);
    s << indent << "maxx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.maxx);
    s << indent << "miny: ";
    Printer<int64_t>::stream(s, indent + "  ", v.miny);
    s << indent << "maxy: ";
    Printer<int64_t>::stream(s, indent + "  ", v.maxy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_1_MESSAGE_GET_POSREQUEST_H
