// Generated by gencpp from file positionserver/newPositionRequest.msg
// DO NOT EDIT!


#ifndef POSITIONSERVER_MESSAGE_NEWPOSITIONREQUEST_H
#define POSITIONSERVER_MESSAGE_NEWPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace positionserver
{
template <class ContainerAllocator>
struct newPositionRequest_
{
  typedef newPositionRequest_<ContainerAllocator> Type;

  newPositionRequest_()
    {
    }
  newPositionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::positionserver::newPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::positionserver::newPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct newPositionRequest_

typedef ::positionserver::newPositionRequest_<std::allocator<void> > newPositionRequest;

typedef boost::shared_ptr< ::positionserver::newPositionRequest > newPositionRequestPtr;
typedef boost::shared_ptr< ::positionserver::newPositionRequest const> newPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::positionserver::newPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::positionserver::newPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace positionserver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::positionserver::newPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::positionserver::newPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::positionserver::newPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::positionserver::newPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::positionserver::newPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::positionserver::newPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::positionserver::newPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::positionserver::newPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::positionserver::newPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "positionserver/newPositionRequest";
  }

  static const char* value(const ::positionserver::newPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::positionserver::newPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::positionserver::newPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::positionserver::newPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::positionserver::newPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::positionserver::newPositionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POSITIONSERVER_MESSAGE_NEWPOSITIONREQUEST_H
