// Generated by gencpp from file ex1_server/rand_pos.msg
// DO NOT EDIT!


#ifndef EX1_SERVER_MESSAGE_RAND_POS_H
#define EX1_SERVER_MESSAGE_RAND_POS_H

#include <ros/service_traits.h>


#include <ex1_server/rand_posRequest.h>
#include <ex1_server/rand_posResponse.h>


namespace ex1_server
{

struct rand_pos
{

typedef rand_posRequest Request;
typedef rand_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rand_pos
} // namespace ex1_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ex1_server::rand_pos > {
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::ex1_server::rand_pos&) { return value(); }
};

template<>
struct DataType< ::ex1_server::rand_pos > {
  static const char* value()
  {
    return "ex1_server/rand_pos";
  }

  static const char* value(const ::ex1_server::rand_pos&) { return value(); }
};


// service_traits::MD5Sum< ::ex1_server::rand_posRequest> should match 
// service_traits::MD5Sum< ::ex1_server::rand_pos > 
template<>
struct MD5Sum< ::ex1_server::rand_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ex1_server::rand_pos >::value();
  }
  static const char* value(const ::ex1_server::rand_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex1_server::rand_posRequest> should match 
// service_traits::DataType< ::ex1_server::rand_pos > 
template<>
struct DataType< ::ex1_server::rand_posRequest>
{
  static const char* value()
  {
    return DataType< ::ex1_server::rand_pos >::value();
  }
  static const char* value(const ::ex1_server::rand_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ex1_server::rand_posResponse> should match 
// service_traits::MD5Sum< ::ex1_server::rand_pos > 
template<>
struct MD5Sum< ::ex1_server::rand_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ex1_server::rand_pos >::value();
  }
  static const char* value(const ::ex1_server::rand_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex1_server::rand_posResponse> should match 
// service_traits::DataType< ::ex1_server::rand_pos > 
template<>
struct DataType< ::ex1_server::rand_posResponse>
{
  static const char* value()
  {
    return DataType< ::ex1_server::rand_pos >::value();
  }
  static const char* value(const ::ex1_server::rand_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EX1_SERVER_MESSAGE_RAND_POS_H
